# Generated by Django 5.1.2 on 2025-03-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIN_REVAMP', '0005_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
