# Generated by Django 5.1.2 on 2025-04-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHIN_REVAMP', '0009_alter_newsletter_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
