# Generated by Django 5.1.2 on 2025-04-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHIN_REVAMP', '0011_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
