# Generated by Django 5.1.2 on 2025-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIN_REVAMP', '0007_contact_delete_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
