# Generated by Django 5.1.2 on 2025-04-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIN_REVAMP', '0008_alter_newsletter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
